"""initial migration

Revision ID: 49ef32ae6b41
Revises: None
Create Date: 2014-08-08 12:38:51.487000

"""

# revision identifiers, used by Alembic.
revision = '49ef32ae6b41'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
